// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Rehtt/gosh/conf"
	"github.com/Rehtt/gosh/database"
	"github.com/Rehtt/gosh/sshd"
)

// Injectors from wire.go:

func Run(confPath2 string) error {
	confConf := conf.Parse(confPath2)
	db := database.Init(confConf)
	error2 := sshd.Run(confConf, db)
	return error2
}
